# Generated by Django 4.0.1 on 2022-01-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('codigo', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=7)),
            ],
        ),
        migrations.DeleteModel(
            name='Tokens',
        ),
    ]
